            ;function yg(){}function zg(){}function Ag(a){return a==null?!1:a!=null?a.m&8||u===a.Zb?!0:a.m?!1:B(yg,a):B(yg,a)}function Bg(a){a:for(var b=a;;)if(b=P(b))b=S(b);else break a;return a}function Cg(a,b,c,d){a=a.g?a.g(b):a.call(null,b);c=Yc(a,c,d);return a.g?a.g(c):a.call(null,c)}
function Dg(a,b,c){if(a!=null&&(a.B&4||u===a.Bb)){var d=Mc(a);return Cg(b,function(){function e(h){return fb(yb(h),d)}var f=null;f=function(h,k){switch(arguments.length){case 1:return e.call(this,h);case 2:return xb(h,k)}throw Error("Invalid arity: "+arguments.length);};f.g=e;f.h=function(h,k){return xb(h,k)};return f}(),wb(a),c)}return Cg(b,yc,a,c)}function Eg(a){return Yc(function(b,c){b.push(c);return b},[],a)}
function Fg(a){if(a!=null&&(a.m&64||u===a.Ta))if(S(a)){a:{var b=[];for(a=P(a);;)if(a!=null)b.push(R(a)),a=S(a);else break a;b=void 0}b=Fc(b)}else b=P(a)?R(a):wd;else b=a;return b}var Gg=function Gg(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Gg.I(0<c.length?new Zb(c.slice(0),0,null):null)};
Gg.I=function(a){var b=a instanceof Zb&&a.s===0?a.i:Eg(a);a=b.length;if(!Vc(a))throw Error(["Argument must be an integer: ",I.g(a)].join(""));if((a&1)!==0){a=Error;var c=I,d=c.g;a:{for(;;){var e=S(b);if(e!=null)b=e;else{b=R(b);break a}}b=void 0}throw a(["No value supplied for key: ",d.call(c,b)].join(""));}return Fc(b)};Gg.V=0;Gg.aa=function(a){return this.I(P(a))};function Hg(a,b){return yb(Yc(function(c,d){d=a.g?a.g(d):a.call(null,d);return xb(c,d)},wb(zc),b))}
var Ig=function Ig(a){switch(arguments.length){case 2:return Ig.h(arguments[0],arguments[1]);case 3:return Ig.l(arguments[0],arguments[1],arguments[2]);case 4:return Ig.G(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Ig.I(arguments[0],arguments[1],arguments[2],arguments[3],4<c.length?new Zb(c.slice(4),0,null):null)}};
Ig.h=function(a,b){if(a instanceof yd){var c=a.state;b=b.g?b.g(c):b.call(null,c);a=zd(a,b)}else a=Eb.h(a,b);return a};Ig.l=function(a,b,c){if(a instanceof yd){var d=a.state;b=b.h?b.h(d,c):b.call(null,d,c);a=zd(a,b)}else a=Eb.l(a,b,c);return a};Ig.G=function(a,b,c,d){if(a instanceof yd){var e=a.state;b=b.l?b.l(e,c,d):b.call(null,e,c,d);a=zd(a,b)}else a=Eb.G(a,b,c,d);return a};
Ig.I=function(a,b,c,d,e){if(a instanceof yd){var f=a.state;b.aa?(c=wc(f,wc(c,wc(d,e))),d=b.V,e=3+Ic(d-2,e),b=e<=d?Jc(b,e,c):b.aa(c)):b=td(b,f,c,d,P(e));a=zd(a,b)}else a=Eb.T(a,b,c,d,e);return a};Ig.aa=function(a){var b=R(a),c=S(a);a=R(c);var d=S(c);c=R(d);var e=S(d);d=R(e);e=S(e);return this.I(b,a,c,d,e)};Ig.V=4;function Jg(){}
function Kg(a){if(a!=null&&a.Fb!=null)a=a.Fb(a);else{var b=Kg[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Kg._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw G("IEncodeJS.-clj-\x3ejs",a);}return a}
function Lg(a,b){if(a!=null?u===a.Eb||(a.wb?0:B(Jg,a)):B(Jg,a))a=Kg(a);else if(typeof a==="string"||typeof a==="number"||a instanceof O||a instanceof Vb)a=b.g?b.g(a):b.call(null,a);else{var c=xc([a]);a=xa();c==null?b=!0:(c!=null?c.m&2||u===c.sb||(c.m?0:B(Ia,c)):B(Ia,c))?b=Ja(c)===0:(b=P(c),b=b==null?!0:b===!1?!0:!1);if(b)a="";else{b=I;var d=b.g,e=new oa,f=new Jb(e);Oe(R(c),f,a);c=P(S(c));for(var h=null,k=0,l=0;;)if(l<k){var m=h.K(null,l);sb(f," ");Oe(m,f,a);l+=1}else if(c=P(c))h=c,Rc(h)?(c=Bb(h),
k=Cb(h),h=c,m=X(c),c=k,k=m):(m=R(h),sb(f," "),Oe(m,f,a),c=S(h),h=null,k=0),l=0;else break;a=d.call(b,e)}}return a}var Mg=function Mg(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Mg.I(arguments[0],1<c.length?new Zb(c.slice(1),0,null):null)};
Mg.I=function(a,b){b=Fg(b);var c=Xb(b,uf,id),d=function h(f){if(f==null)return null;if(f!=null?u===f.Eb||(f.wb?0:B(Jg,f)):B(Jg,f))return Kg(f);if(f instanceof O)return c.g?c.g(f):c.call(null,f);if(f instanceof Vb)return I.g(f);if(Oc(f)){var k={};f=P(f);for(var l=null,m=0,n=0;;)if(n<m){var q=l.K(null,n),r=Dc(q,0),w=Dc(q,1);q=k;r=Lg(r,d);w=h(w);q[r]=w;n+=1}else if(f=P(f))Rc(f)?(m=Bb(f),f=Cb(f),l=m,m=X(m)):(l=R(f),m=Dc(l,0),n=Dc(l,1),l=k,m=Lg(m,d),n=h(n),l[m]=n,f=S(f),l=null,m=0),n=0;else break;return k}if(Ag(f)){k=
[];f=P(Ad.h(h,f));l=null;for(n=m=0;;)if(n<m)q=l.K(null,n),k.push(q),n+=1;else if(f=P(f))l=f,Rc(l)?(f=Bb(l),n=Cb(l),l=f,m=X(f),f=n):(f=R(l),k.push(f),f=S(l),l=null,m=0),n=0;else break;return k}return f};return d(a)};Mg.V=1;Mg.aa=function(a){var b=R(a);a=S(a);return this.I(b,a)};function Ng(){}
function Og(a,b){if(a!=null&&a.Db!=null)a=a.Db(a,b);else{var c=Og[t(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Og._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw G("IEncodeClojure.-js-\x3eclj",a);}return a}
function Pg(a){var b=xc([bg,!0]),c=Fg(b);c=Wb(c,bg);var d=z(c)?hd:I;return function h(f){return(f!=null?u===f.$b||(f.wb?0:B(Ng,f)):B(Ng,f))?Og(f,ud(Gg,b)):(f==null?0:f!=null?f.m&64||u===f.Ta||(f.m?0:B(zg,f)):B(zg,f))?Bg(Ad.h(h,f)):$d(f)?new Zd(h($a(f)),h(ab(f))):Ag(f)?Dg(Bc(f),Ad.g(h),f):Ea(f)?yb(Yc(function(k,l){l=h(l);return xb(k,l)},wb(zc),f)):(f==null?null:f.constructor)===Object?yb(Yc(function(k,l){var m=d.g?d.g(l):d.call(null,l);l=h(la.call(null,f,l));return zb(k,m,l)},wb(wd),ka.call(null,f))):
f}(a)}var Qg={};function Rg(a,b,c,d){return new x(null,6,[Lf,b,ig,Hg(c,a),lf,d,Jf,d,eg,d,Xf,20],null)}function Sg(a){return new Nd(null,5,5,Qd,[Rg(a,"Goals",hf,"#eec900"),Rg(a,"Shots",zf,"#ff7300"),Rg(a,"Passes",xf,"#00bfff"),Rg(a,"Carries",hg,"#82ca9d"),Rg(a,"Takeaways",Hf,"#ff1493")],null)}
function Tg(a){return new x(null,4,[kf,new x(null,2,[ff,"rgba(128,128,128,0.20)",Nf,.5],null),$f,new x(null,3,[Qf,!0,qf,2,ff,"#696969"],null),Pf,new x(null,1,[Af,new x(null,1,[Bf,18],null)],null),Cf,new x(null,3,[Qf,!0,gg,a,Af,new x(null,1,[Bf,20],null)],null)],null)}
function Ug(){var a=Vg;return new x(null,6,[af,!0,Of,!1,tf,new x(null,3,[pf,"index",Zf,"x",Sf,!0],null),yf,new x(null,2,[If,new x(null,2,[gf,.2,nf,!1],null),Tf,new x(null,6,[cg,"#ffffff",Yf,2,Ef,3,fg,"#ffffff",Ff,3,Gf,8],null)],null),Mf,new x(null,2,[rf,new x(null,2,[Rf,"top",$e,new x(null,3,[Af,new x(null,1,[Bf,20],null),Kf,1,of,20],null)],null),dg,new x(null,5,[Kf,1,of,15,jf,10,ef,new x(null,1,[Bf,18],null),wf,new x(null,1,[Cf,function(b){b=b[0];if(z(b)){b=parseInt(b.dataIndex);var c=tc(a.J?a.J():
a.call(null),b);b=bf.g(c);var d=ag.g(c);c=mf.g(c);b=[I.g(b)," @",I.g(d),"\n",I.g(c)].join("")}else b=null;return b}],null)],null)],null),vf,new x(null,2,[Wf,Tg("Game #"),Ye,Tg("Count")],null)],null)};var Wg={};if(typeof Qg==="undefined"||typeof Wg==="undefined"||typeof Xg==="undefined")var Xg=new yd(df);if(typeof Qg==="undefined"||typeof Wg==="undefined"||typeof Yg==="undefined")var Yg=Pg(window.GAME_STATS_DATA);if(typeof Qg==="undefined"||typeof Wg==="undefined"||typeof Vg==="undefined")var Vg=Pg(window.CUMULATIVE_GAME_STATS_DATA);function Zg(){var a=document.getElementById("toggle-game-graph"),b=cc.h(cb(Xg),df)?"Show per-game":"Show cumulative";return a.textContent=b}
function $g(a){Ig.h(Xg,function(c){return cc.h(c,df)?Ze:df});var b=cc.h(cb(Xg),df)?Vg:Yg;a.data.labels=Mg(Hg(Uf,b));a.data.datasets=Mg(Sg(b));a.update.call(a);a.update();return Zg()}function ah(){var a=document.getElementById("game-graph").getContext("2d"),b=Mg(new x(null,3,[sf,"line",ig,new x(null,2,[$e,Hg(Uf,Vg),cf,Sg(Vg)],null),Vf,Ug()],null));return new Chart(a,b)}function bh(){var a=ah();return jg("toggle-game-graph",function(){return $g(a)})}da("landing.game_graph.init",bh);bh();